graph TD

A1["A P1 P2 L E"] --> C1["APPLE"]
A2["A P2 P1 L E"] --> C1["APPLE"]

B1["P1 A P2 L E"] --> C2["PAPLE"]
B2["P2 A P1 L E"] --> C2["PAPLE"]

C3a["P1 P2 A L E"] --> C3["PPALE"]
C3b["P2 P1 A L E"] --> C3["PPALE"]

D1["A P1 L P2 E"] --> C4["APLPE"]
D2["A P2 L P1 E"] --> C4["APLPE"]

E1["L P1 P2 A E"] --> C5["LPPAE"]
E2["L P2 P1 A E"] --> C5["LPPAE"]
